is4inmem:
  build: is4inmem
  environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://*:5000
  ports:
    - 5000:5000

testapi:
  build: testapi
  environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://*:5004
  ports:
    - 5004:5004
  links:
    - is4inmem:localhost
