# post http://localhost:5000/connect/token 
# content-type: application/x-www-form-urlencoded

# client_id=client&client_secret=511536EF-F270-4058-80CA-1C89C192F69A&grant_type=client_credentials


@token = Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY4MjZmOTQyZjQ4YzQ5ZTdiYjg3NjczYzBlNjdlMTg5IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MTI1NjkwODEsImV4cCI6MTUxMjU3MjY4MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbImFwaTEiXX0.qvosXc25y8Gz57dg03tHyP_ET4VI_TIzqMbrzRW-o6pd1Yb_ZUiwF7-bN6wK_AjsMdEiuAH-1rg7RqBHS6qFu_35k39q-v-NxTnMxrjt9iTl8gGQR7g6r06qDdpGz0YDx3XnLlO590N435jxs6lP1th1I3UiiEQ1vKKtpc-sn8oAEI2xwEzKnTkGP9oM0YdFwrEQbCPjg0UK_EbtzTexzBu3BQ4AQf6X_cWqvq6Cin8EdUNMSf9tE8oANkoc7uDlGNsyh_UR4odCz5T6E-MVRk1zk31C-Yrvv57KGZFcPPFasN4QOwb96KVo28tG_LTFhHoIARgcmSla5Ha0NB-tkg

get http://localhost:5004/api/Values
Authorization: {{token}}


